import type { KeyEventHandler } from "./types";
import type { WrappedTerminal } from "./term_ctl";
import { AbstractFileSystem } from "./filesystem";
export declare const execute_next_line: KeyEventHandler;
export declare const delete_character: KeyEventHandler;
export declare const previous_history: KeyEventHandler;
export declare const next_history: KeyEventHandler;
export declare const move_cursor_left: KeyEventHandler;
export declare const move_cursor_right: KeyEventHandler;
export declare const mark_modified: KeyEventHandler;
export declare const tab_completion: KeyEventHandler;
export declare const register_builtin_key_handlers: (term: WrappedTerminal) => void;
export declare const change_prompt: (path: string, fs: AbstractFileSystem, term: WrappedTerminal) => void;
export declare const register_builtin_fs_handlers: (term: WrappedTerminal) => void;
